#!/usr/bin/env bash
# Build a kubeconfig that authenticates through **application default
# credentials**, for a CI job that has a workload-identity federation and no
# `gcloud auth login`.
#
# The laptop does the opposite on purpose (AGENTS.md, "Cluster access"): there,
# kubectl must use the human identity, because Terraform's identity is a service
# account key and `gke-gcloud-auth-plugin` shells out to `gcloud config
# config-helper`, which crashes on an active service-account credential. That
# crash is avoidable, and the flag that avoids it is the point of this file:
# `--use_application_default_credentials=true` tells the plugin to read the
# credentials it was given instead of asking gcloud what a human logged in as.
#
# So the same cluster is reached two ways by design: a human through the gcloud
# configuration, CI through ADC. Neither identity is a fallback for the other.
set -euo pipefail

cluster="${CLUSTER_NAME:-learn-anything}"
region="${CLUSTER_REGION:-asia-east2}"
project="${PROJECT_ID:?PROJECT_ID must be set}"
out="${1:-.kubeconfig-ci}"

# Read the cluster rather than guess at it: endpoint and CA come from the API, so
# this file cannot drift into a kubeconfig that points at a cluster that no
# longer exists.
# A file, not a command-substituted variable: the generator below reads it, and a
# heredoc owns stdin, so the JSON has to arrive some other way.
describe="$(mktemp)"
trap 'rm -f "$describe"' EXIT
gcloud container clusters describe "$cluster" --region="$region" \
  --project="$project" --format=json >"$describe"

# The heredoc is the program, so the arguments are argv and the cluster JSON comes
# in through the environment. (`python3 "$describe"` would run the JSON as Python,
# which is a confusing way to find that out.)
CLUSTER_JSON="$describe" python3 - "$out" "$cluster" "$region" "$project" <<'PY'
import json, os, sys, pathlib
out, cluster, region, project = sys.argv[1:5]
c = json.load(open(os.environ["CLUSTER_JSON"]))
server = c["endpoint"]
ca = c["selfLink"]  # only for the comment below
pathlib.Path(out).write_text(f"""apiVersion: v1
kind: Config
# Generated by scripts/ci-kubeconfig.sh — do not edit, and do not commit it.
# Cluster: {c['id']} ({region}) in {project}
# Auth: ADC via gke-gcloud-auth-plugin (CI), not the local gcloud configuration.
clusters:
- name: {cluster}
  cluster:
    server: https://{server}
    certificate-authority-data: {c['masterAuth']['clusterCaCertificate']}
contexts:
- name: {cluster}
  context:
    cluster: {cluster}
    user: {cluster}-adc
current-context: {cluster}
users:
- name: {cluster}-adc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      args:
        - --use_application_default_credentials=true
      provideClusterInfo: true
      interactiveMode: Never
""")
PY
echo "wrote $out (cluster=$cluster region=$region project=$project)" >&2
